// tailwind.config.js
module.exports = {
    darkMode: 'class',
    content: [
        './frontend/views/**/*.php',
        './frontend/widgets/**/*.js',
        './frontend/web/js/**/*.js',
        './frontend/views/layouts/*.php',
    ],
    theme: {
        extend: {
            colors: {
                'error-container': '#ffdad6',
                'on-tertiary': '#ffffff',
                'error': '#ba1a1a',
                'on-tertiary-fixed-variant': '#3a485c',
                'secondary': '#006a61',
                'surface-container-highest': '#e0e3e5',
                'outline-variant': '#c6c6cd',
                'surface-container-high': '#e6e8ea',
                'tertiary-container': '#0d1c2f',
                'surface-container-lowest': '#ffffff',
                'tertiary-fixed-dim': '#b9c7e0',
                'surface-dim': '#d8dadc',
                'primary': '#000000',
                'primary-fixed': '#dae2fd',
                'surface': '#f7f9fb',
                'secondary-fixed-dim': '#6bd8cb',
                'inverse-primary': '#bec6e0',
                'inverse-surface': '#2d3133',
                'on-secondary-container': '#006f66',
                'on-error': '#ffffff',
                'surface-container-low': '#f2f4f6',
                'tertiary-fixed': '#d5e3fd',
                'surface-variant': '#e0e3e5',
                'background': '#f7f9fb',
                'on-secondary-fixed': '#00201d',
                'primary-fixed-dim': '#bec6e0',
                'surface-bright': '#f7f9fb',
                'on-primary-fixed-variant': '#3f465c',
                'on-primary-container': '#7c839b',
                'surface-tint': '#565e74',
                'on-background': '#191c1e',
                'outline': '#76777d',
                'on-surface': '#191c1e',
                'inverse-on-surface': '#eff1f3',
                'on-error-container': '#93000a',
                'primary-container': '#131b2e',
                'on-primary': '#ffffff',
                'on-surface-variant': '#45464d',
                'tertiary': '#000000',
                'surface-container': '#eceef0',
                'on-tertiary-container': '#76859b',
                'on-tertiary-fixed': '#0d1c2f',
                'secondary-container': '#86f2e4',
                'on-secondary': '#ffffff',
                'on-secondary-fixed-variant': '#005049',
                'secondary-fixed': '#89f5e7',
                'on-primary-fixed': '#131b2e',
            },
            borderRadius: {
                DEFAULT: '0.125rem',
                lg: '0.25rem',
                xl: '0.5rem',
                full: '0.75rem',
            },
            spacing: {
                'margin-mobile': '16px',
                'margin-desktop': '48px',
                xs: '8px',
                sm: '16px',
                md: '24px',
                lg: '40px',
                xl: '64px',
                base: '4px',
                gutter: '24px',
            },
            fontFamily: {
                'body-md': ['Inter', 'sans-serif'],
                'headline-lg': ['Inter', 'sans-serif'],
                'headline-md': ['Inter', 'sans-serif'],
                'label-caps': ['Inter', 'sans-serif'],
                display: ['Inter', 'sans-serif'],
                'data-mono': ['JetBrains Mono', 'monospace'],
                'body-lg': ['Inter', 'sans-serif'],
                'headline-lg-mobile': ['Inter', 'sans-serif'],
            },
            fontSize: {
                'body-md': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
                'headline-lg': ['28px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
                'headline-md': ['20px', { lineHeight: '1.4', letterSpacing: '-0.01em', fontWeight: '600' }],
                'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '700' }],
                display: ['36px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
                'data-mono': ['13px', { lineHeight: '1.5', fontWeight: '400' }],
                'body-lg': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
                'headline-lg-mobile': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
            },
        },
    },
    plugins: [
        require('@tailwindcss/forms'),
        require('@tailwindcss/container-queries'),
    ],
};